# Generated by Django 3.0.6 on 2020-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200601_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletheme',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Основная тема'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Тема'),
        ),
    ]
