# Generated by Django 3.0.6 on 2020-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200602_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletheme',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная тема'),
        ),
    ]
